language: python

virtualenv:
  system_site_packages: true

before_install:
  - pip install -r requirements.txt
  - pip install flake8
  - sudo apt-get install tidy

script:
  - flake8 -v *.py
  - tidy -e *.html
